# lifesub-web/deployment/manifest/deployments/lifesub-web-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifesub-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lifesub-web
  template:
    metadata:
      labels:
        app: lifesub-web
    spec:
      containers:
        - name: lifesub-web
          image: dg0200cr.azurecr.io/lifesub/lifesub-web:20250217202235
          imagePullPolicy: Always
          ports:
            - containerPort: 18080
          resources:
            requests:
              cpu: 256m
              memory: 256Mi
            limits:
              cpu: 1024m
              memory: 1024Mi
